package com.example.domain.entity

import java.util.Date

data class TutorEntity(
    var id : String,
    var level : String? = "",
    var email : String? = "",
    var google : String? = "",
    var facebook : String? = "",
    var apple : String? = "",
    var avatar : String? = "",
    var name : String? = "",
    var country : String? = "",
    var phone : String? = "",
    var language : String? = "",
    var birthDay : Date? = null,
    var requestPassword : Boolean? = false,
    var isActivated : Boolean? = false,
    var isPhoneActivated : Boolean? = false,
    var requireNote : String? = "",
    var timezone : Int? = 0,
    var phoneAuth : String? = "",
    var isPhoneAuthActivated : Boolean? = false,
    var canSendMessage : Boolean? = false,
    var isPublicRecord : Boolean? = false,
    var caredByStaffId : String? = "",
    var createdAt : Date? = null,
    var updatedAt : Date? = null,
    var deletedAt : String? = "",
    var studentGroupId : String? = "",
    var userId : String? = "",
    var video : String? = "",
    var bio : String? = "",
    var education : String? = "",
    var experience : String? = "",
    var profession : String? = "",
    var accent : String? = "",
    var targetStudent : String? = "",
    var interests : String? = "",
    var languages : String? = "",
    var specialties : String? = "",
    var resume : String? = "",
    var rating : Double?    = 0.0,
    var isNative : Boolean? = false,
    var price : Double? = 0.0,
    var isOnline : Boolean?     = false
)