package com.example.feat.home.model

import com.example.feat.home.entity.TutorEntity
import com.squareup.moshi.JsonClass
import java.util.Date

@JsonClass(generateAdapter = true)
data class TutorModel(
    var id : String,
    var level : String?,
    var email : String?,
    var google : String?,
    var facebook : String?,
    var apple : String?,
    var avatar : String?,
    var name : String?,
    var country : String?,
    var phone : String?,
    var language : String?,
    var birthDay : Date?,
    var requestPassword : Boolean?,
    var isActivated : Boolean?,
    var isPhoneActivated : Boolean?,
    var requireNote : String?,
    var timezone : Int?,
    var phoneAuth : String?,
    var isPhoneAuthActivated : Boolean?,
    var canSendMessage : Boolean?,
    var isPublicRecord : Boolean?,
    var caredByStaffId : String?,
    var createdAt : Date?,
    var updatedAt : Date?,
    var deletedAt : String?,
    var studentGroupId : String?,
    var userId : String?,
    var video : String?,
    var bio : String?,
    var education : String?,
    var experience : String?,
    var profession : String?,
    var accent : String?,
    var targetStudent : String?,
    var interests : String?,
    var languages : String?,
    var specialties : String?,
    var resume : String?,
    var rating : Double?,
    var isNative : Boolean?,
    var price : Double?,
    var isOnline : Boolean?
){
    fun toEntity(): TutorEntity {
        return TutorEntity(
            id = this.id,
            level = this.level,
            email = this.email,
            google = this.google,
            facebook = this.facebook,
            apple = this.apple,
            avatar = this.avatar,
            name = this.name,
            country = this.country,
            phone = this.phone,
            language = this.language,
            birthDay = this.birthDay,
            requestPassword = this.requestPassword,
            isActivated = this.isActivated,
            isPhoneActivated = this.isPhoneActivated,
            requireNote = this.requireNote,
            timezone = this.timezone,
            phoneAuth = this.phoneAuth,
            isPhoneAuthActivated = this.isPhoneAuthActivated,
            canSendMessage = this.canSendMessage,
            isPublicRecord = this.isPublicRecord,
            caredByStaffId = this.caredByStaffId,
            createdAt = this.createdAt,
            updatedAt = this.updatedAt,
            deletedAt = this.deletedAt,
            studentGroupId = this.studentGroupId,
            userId = this.userId,
            video = this.video,
            bio = this.bio,
            education = this.education,
            experience = this.experience,
            profession = this.profession,
            accent = this.accent,
            targetStudent = this.targetStudent,
            interests = this.interests,
            languages = this.languages,
            specialties = this.specialties,
            resume = this.resume,
            rating = this.rating,
            isNative = this.isNative,
            price = this.price,
            isOnline = this.isOnline
        )
    }
}
